from __future__ import annotations
import json
from vulnscout.models.schemas import Scan, Vulnerability

def format_report(scan: Scan, vulns: list[Vulnerability], fmt: str = "json") -> tuple[str, str]:
    if fmt == "json":
        return _format_json(scan, vulns), "application/json"
    elif fmt == "sarif":
        return _format_sarif(scan, vulns), "application/json"
    elif fmt == "markdown":
        return _format_markdown(scan, vulns), "text/markdown"
    return _format_json(scan, vulns), "application/json"

def _format_json(scan: Scan, vulns: list[Vulnerability]) -> str:
    return json.dumps({"scan_id": scan.id, "language": scan.language, "source_path": scan.source_path,
        "created_at": scan.created_at.isoformat() if scan.created_at else None,
        "summary": {"total_files": scan.total_files, "scanned_files": scan.scanned_files,
            "critical": scan.vuln_count_critical, "high": scan.vuln_count_high,
            "medium": scan.vuln_count_medium, "low": scan.vuln_count_low},
        "vulnerabilities": [{"id": v.id, "file_path": v.file_path, "line_start": v.line_start,
            "line_end": v.line_end, "cwe_id": v.cwe_id, "severity": v.severity,
            "title": v.title, "description": v.description} for v in vulns]}, indent=2, ensure_ascii=False)

def _format_sarif(scan: Scan, vulns: list[Vulnerability]) -> str:
    results = []
    for v in vulns:
        results.append({"ruleId": v.cwe_id or "unknown", "level": {"critical": "error", "high": "error", "medium": "warning", "low": "note"}.get(v.severity, "warning"),
            "message": {"text": f"{v.title}: {v.description}" if v.description else v.title},
            "locations": [{"physicalLocation": {"artifactLocation": {"uri": v.file_path}, "region": {"startLine": v.line_start or 1, "endLine": v.line_end or v.line_start or 1}}}]})
    return json.dumps({"$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [{"tool": {"driver": {"name": "VulnScout", "version": "0.1.0", "informationUri": "https://github.com/yujh129/vulnscout"}}, "results": results}]}, indent=2)

def _format_markdown(scan: Scan, vulns: list[Vulnerability]) -> str:
    lines = [f"# VulnScout Scan Report\n", f"**Scan ID:** {scan.id}\n**Source:** {scan.source_path}\n**Language:** {scan.language or 'auto'}\n**Date:** {scan.created_at.strftime('%Y-%m-%d %H:%M:%S') if scan.created_at else 'N/A'}\n",
        f"\n## Summary\n| Severity | Count |\n|----------|-------|\n| Critical | {scan.vuln_count_critical} |\n| High | {scan.vuln_count_high} |\n| Medium | {scan.vuln_count_medium} |\n| Low | {scan.vuln_count_low} |\n\n**Files:** {scan.scanned_files}/{scan.total_files} scanned\n"]
    for i, v in enumerate(vulns, 1):
        lines.append(f"\n### {i}. [{v.severity.upper()}] {v.title}\n- **File:** `{v.file_path}`\n" + (f"- **Line:** {v.line_start}-{v.line_end or v.line_start}\n" if v.line_start else "") + (f"- **CWE:** {v.cwe_id}\n" if v.cwe_id else "") + (f"- **Description:** {v.description}\n" if v.description else ""))
    lines.append("\n---\n*Generated by VulnScout v0.1.0*")
    return "\n".join(lines)
